# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/mathe/Documents/School/cos214/Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/mathe/Documents/School/cos214

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/mathe/Documents/School/cos214/CMakeFiles /mnt/c/Users/mathe/Documents/School/cos214//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/mathe/Documents/School/cos214/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project

# Build rule for target.
Project: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Project
.PHONY : Project

# fast build rule for target.
Project/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/build
.PHONY : Project/fast

AbstractTable.o: AbstractTable.cpp.o
.PHONY : AbstractTable.o

# target to build an object file
AbstractTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/AbstractTable.cpp.o
.PHONY : AbstractTable.cpp.o

AbstractTable.i: AbstractTable.cpp.i
.PHONY : AbstractTable.i

# target to preprocess a source file
AbstractTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/AbstractTable.cpp.i
.PHONY : AbstractTable.cpp.i

AbstractTable.s: AbstractTable.cpp.s
.PHONY : AbstractTable.s

# target to generate assembly for a file
AbstractTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/AbstractTable.cpp.s
.PHONY : AbstractTable.cpp.s

App.o: App.cpp.o
.PHONY : App.o

# target to build an object file
App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/App.cpp.o
.PHONY : App.cpp.o

App.i: App.cpp.i
.PHONY : App.i

# target to preprocess a source file
App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/App.cpp.i
.PHONY : App.cpp.i

App.s: App.cpp.s
.PHONY : App.s

# target to generate assembly for a file
App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/App.cpp.s
.PHONY : App.cpp.s

Customer.o: Customer.cpp.o
.PHONY : Customer.o

# target to build an object file
Customer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Customer.cpp.o
.PHONY : Customer.cpp.o

Customer.i: Customer.cpp.i
.PHONY : Customer.i

# target to preprocess a source file
Customer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Customer.cpp.i
.PHONY : Customer.cpp.i

Customer.s: Customer.cpp.s
.PHONY : Customer.s

# target to generate assembly for a file
Customer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Customer.cpp.s
.PHONY : Customer.cpp.s

Engine.o: Engine.cpp.o
.PHONY : Engine.o

# target to build an object file
Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Engine.cpp.o
.PHONY : Engine.cpp.o

Engine.i: Engine.cpp.i
.PHONY : Engine.i

# target to preprocess a source file
Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Engine.cpp.i
.PHONY : Engine.cpp.i

Engine.s: Engine.cpp.s
.PHONY : Engine.s

# target to generate assembly for a file
Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Engine.cpp.s
.PHONY : Engine.cpp.s

Facade.o: Facade.cpp.o
.PHONY : Facade.o

# target to build an object file
Facade.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Facade.cpp.o
.PHONY : Facade.cpp.o

Facade.i: Facade.cpp.i
.PHONY : Facade.i

# target to preprocess a source file
Facade.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Facade.cpp.i
.PHONY : Facade.cpp.i

Facade.s: Facade.cpp.s
.PHONY : Facade.s

# target to generate assembly for a file
Facade.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Facade.cpp.s
.PHONY : Facade.cpp.s

Floor.o: Floor.cpp.o
.PHONY : Floor.o

# target to build an object file
Floor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Floor.cpp.o
.PHONY : Floor.cpp.o

Floor.i: Floor.cpp.i
.PHONY : Floor.i

# target to preprocess a source file
Floor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Floor.cpp.i
.PHONY : Floor.cpp.i

Floor.s: Floor.cpp.s
.PHONY : Floor.s

# target to generate assembly for a file
Floor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Floor.cpp.s
.PHONY : Floor.cpp.s

Mediator.o: Mediator.cpp.o
.PHONY : Mediator.o

# target to build an object file
Mediator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Mediator.cpp.o
.PHONY : Mediator.cpp.o

Mediator.i: Mediator.cpp.i
.PHONY : Mediator.i

# target to preprocess a source file
Mediator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Mediator.cpp.i
.PHONY : Mediator.cpp.i

Mediator.s: Mediator.cpp.s
.PHONY : Mediator.s

# target to generate assembly for a file
Mediator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Mediator.cpp.s
.PHONY : Mediator.cpp.s

Table.o: Table.cpp.o
.PHONY : Table.o

# target to build an object file
Table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Table.cpp.o
.PHONY : Table.cpp.o

Table.i: Table.cpp.i
.PHONY : Table.i

# target to preprocess a source file
Table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Table.cpp.i
.PHONY : Table.cpp.i

Table.s: Table.cpp.s
.PHONY : Table.s

# target to generate assembly for a file
Table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Table.cpp.s
.PHONY : Table.cpp.s

Waiter.o: Waiter.cpp.o
.PHONY : Waiter.o

# target to build an object file
Waiter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Waiter.cpp.o
.PHONY : Waiter.cpp.o

Waiter.i: Waiter.cpp.i
.PHONY : Waiter.i

# target to preprocess a source file
Waiter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Waiter.cpp.i
.PHONY : Waiter.cpp.i

Waiter.s: Waiter.cpp.s
.PHONY : Waiter.s

# target to generate assembly for a file
Waiter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/Waiter.cpp.s
.PHONY : Waiter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Project"
	@echo "... AbstractTable.o"
	@echo "... AbstractTable.i"
	@echo "... AbstractTable.s"
	@echo "... App.o"
	@echo "... App.i"
	@echo "... App.s"
	@echo "... Customer.o"
	@echo "... Customer.i"
	@echo "... Customer.s"
	@echo "... Engine.o"
	@echo "... Engine.i"
	@echo "... Engine.s"
	@echo "... Facade.o"
	@echo "... Facade.i"
	@echo "... Facade.s"
	@echo "... Floor.o"
	@echo "... Floor.i"
	@echo "... Floor.s"
	@echo "... Mediator.o"
	@echo "... Mediator.i"
	@echo "... Mediator.s"
	@echo "... Table.o"
	@echo "... Table.i"
	@echo "... Table.s"
	@echo "... Waiter.o"
	@echo "... Waiter.i"
	@echo "... Waiter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

