name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: rm -rf ${{github.workspace}}/build/*

    - name: Build
    - working-directory: ${{github.workspace}}/Code/Project/build
      run: make
