name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository content
      uses: actions/checkout@v3
    - working-directory: ${{github.workspace}}/Code/Project/build
      run: make Project
