name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: |
        rm -rf ${{github.workspace}}/Code/Project/build/*
        cmake -S ${{github.workspace}}/Code/Project/Project -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        
    - name: Build
      working-directory: ${{github.workspace}}/Code/Project/build
      run: make
