name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: |
        rm -rf ${{github.workspace}}/build/*
        cmake -S ${{github.workspace}} -B ${{github.workspace}}/Code/Project/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
    - working-directory: ${{github.workspace}}/Code/Project/build
      run: make
