name: Makefile CI

on:
  push:
    branches: [ "main", "Mathenda", "Sage", "ntando", "SelenatorXo", "Rea", "Fentse" ]
  pull_request:
    branches: [ "main", "Mathenda", "Sage", "ntando", "SelenatorXo", "Rea", "Fentse" ]
    
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: |
        rm -rf ${{github.workspace}}/Code/Project/build/*
        cmake -S ${{github.workspace}}/Code/Project/Project -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: make
